[project]
name = "certbot-dns-admtools"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "certbot>=3.0.1",
    "zope>=5.11.1",
]
